### PR TITLE
Remove generated figs from tree and update gh actions versions

### PR DESCRIPTION
**Pull request by nvaytet**
When we build the book locally, git says that those png figures have changed.
They are generated by the `make_figures.py` script, so the don't need to be in the source tree?

### CODE REVIEW

**Comment by jl-wynen** [comment]
I only see `make_figures.ipynb`, not `make_figures.py`.
The notebook will be executed by nbconvert. But I don't think we can rely on this happening before the notebooks that need the figures are executed. Especially because it is not included in the table of contents.

Is there a way to make books run a script before building any pages?

**Comment by nvaytet** [comment]
> I only see make_figures.ipynb, not make_figures.py.

Yes, that's what I meant. We could turn that notebook into a script, and run it manually before building the book, or I could make the figure generation part of the notebooks that use them.

**Comment by jl-wynen** [comment]
I'd say go with turning `make_figures` into a script. And set up make (or snakemake if you like) to build the book. Relying on people to run an extra command will cause a lot of frustration.

**Comment by nvaytet** [comment]
> Relying on people to run an extra command will cause a lot of frustration.

For that reason, I'm making the figure generation part of the notebook.

**Review by jl-wynen — APPROVED** [review]

**Pull request merged**
