### PR TITLE
Removed pin from McStasScript version.

### PR DESCRIPTION
**Pull request by mads-bertelsen**
Checking if running latest McStasScript would fix configuration issue.

### CODE REVIEW

**Review by nvaytet — CHANGES_REQUESTED** [review]
It seems the book is still not building correctly. The Mcstas notebooks have not outputs/figures, and the subsequent reduction parts can't find the results to load.

**Comment by mads-bertelsen** [comment]
Yes, it's as if those notebooks are not even executed. I am looking for any reason why that may be, perhaps there is some cell metadata that prevents them from being executed.

**Comment by nvaytet** [comment]
If I build locally, it seems to run...

**Comment by mads-bertelsen** [comment]
I found the issue, there was an outdated configuration at the top of two notebooks. Currently the setup in the GitHub workflow installs a pinned McStas 3.4 and configuration in the notebooks searched for a 3.3. I think we will just pin it to 3.4 for this years school even though a 3.5 might make it in time.

The book builds correctly now with data flowing all the way to nice fits in analysis!

**Review by nvaytet — APPROVED** [review]

**Pull request merged**
